@JobTrackerAPI_HostAddress = http://localhost:5100


POST {{JobTrackerAPI_HostAddress}}/api/JobApplications
Content-Type: application/json

{
  "company": "Eksempel AS",
  "position": "Juniorutvikler",
  "location": "Oslo",
  "dateApplied": "2026-09-16",
  "deadline": "2026-10-03",
  "status": "Applied",
  "notes": "Eksempel på jobbsøknad"
}

###